name: "go-junit-report"
on:
  pull_request: {}

jobs:
  gotestsum:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: run gotestsum
        run: |
          cd ./gotestsum
          go test -json ./... 2>&1 | go run github.com/jstemmer/go-junit-report/v2@latest -parser gojson > unit-test.xml
      - name: JUnit Report Action
        uses: mikepenz/action-junit-report@v3.7.6
        if: always()
        with:
          report_paths: ./gotestsum/unit-test.xml
