name: "gotestsum"
on:
  pull_request: {}

jobs:
  gotestsum:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: run gotestsum
        runs: |
          cd ./gotestsum
          go run gotest.tools/gotestsum@latest --junitfile unit-test.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.7.0
        with:
          files: ./gotestsum/unit-test.xml
